<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1539966995317' stop='1539966995349'>
    <name>Order:</name>
    <title>Order:</title>
    <test-cases>
        <test-case start='1539966995318' status='failed' stop='1539966995347'>
            <name>Place a Delivery Order</name>
            <title>Place a Delivery Order</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
            <failure>
                <message>Can't connect to WebDriver.
                Error: connect ECONNREFUSED 127.0.0.1:4723
                
                Please make sure Selenium Server (ChromeDriver or PhantomJS) is running and accessible</message>
                <stack-trace>Error: connect ECONNREFUSED 127.0.0.1:4723
                    at new RuntimeError (/usr/local/lib/node_modules/webdriverio/build/lib/utils/ErrorHandler.js:143:12)
                    at Request._callback (/usr/local/lib/node_modules/webdriverio/build/lib/utils/RequestHandler.js:330:43)
                    at self.callback (/usr/local/lib/node_modules/webdriverio/node_modules/request/request.js:185:22)
                    at emitOne (events.js:116:13)
                    at Request.emit (events.js:211:7)
                    at Request.onRequestError (/usr/local/lib/node_modules/webdriverio/node_modules/request/request.js:881:8)
                    at emitOne (events.js:121:20)
                    at ClientRequest.emit (events.js:211:7)
                    at Socket.socketErrorListener (_http_client.js:387:9)
                    at emitOne (events.js:116:13)</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>